name: Test 🧪
on:
  workflow_dispatch:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: # matches refs/heads/main``
      - "main"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      ImageOS: ubuntu22
    container: node:16.20.1-slim
    name: Create Coverage Report
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.13.4"
          otp-version: "24"

      - name: Restore dependencies cache
        uses: actions/cache@v3.3.1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile dependencies
        run: mix deps.compile

      - name: Generating XML
        run: mix coveralls.json
        # todo: remove after tests are added
        continue-on-error: true
        env:
          MIX_ENV: test
          DB_HOSTNAME: postgres
          DB_NAME: test
          DB_USER: postgres
          DB_PASSWORD: postgres
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
          directory: cover
          fail_ci_if_error: true
          verbose: true
